[build]
  command = "npm run build"  
  publish = "build/"
  functions = "functions"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, DELETE, OPTIONS"

[dev]
  framework = "create-react-app"
  targetPort = 3000
  autoLaunch = false